### ISSUE TITLE
Re-Onboard device after new created datapoints in mindsphere

### ISSUE THREAD

**Issue by EliasReuter** [mindsphere/node-red-contrib-mindconnect#95]
We're connecting an IoT2040 to mindsphere with NodeRed and this node installed in it.
Onboarding and uploading data works fine.
Once we onboarded our device and create our datasources and datapoints in Mindsphere, we are able to send data from our mentioned IOT2040.
The problem is when we create new datapoints in Mindsphere and add those given datapointIDs to our to-send json. The mindconnect node only accepts these new datapoints if we cancel the mentioned onboarding that was already working and create a new SHARED SECRET to onboard the IoT2040 again. Then the new datasources/datapoints are updated correctlly.

Thank you 👍

**Comment by sn0wcat** [comment]
You could include msg._forceGetConfig=true; in the input message to force the node to get the configuration from mindsphere again instead of completely re-onboarding.

![image](https://user-images.githubusercontent.com/1426617/86774355-c26f0e80-c056-11ea-8856-9f9afdf31682.png)

Don't forget to remove the _forceGetConfig after the config was updated otherwise you will create a lot of unnecessary load on your tenant....

**Comment by EliasReuter** [comment]
Great!
Adding "msg._forceGetConfig=true;" and deploying updated the datapoints config.
Once updated, removing that line and deploying to the previous state work as fine too.

Thank you 🥇
